steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - defy-address-capture
  - --gen2
  - --run-service-account=${_SERVICE_ACCOUNT}
  - --vpc-connector=${_VPC_CONNECTOR}
  - --region=us-central1
  - --source=./backend/src
  - --trigger-http
  - --entry-point=entrypoint
  - --allow-unauthenticated
  - --runtime=python39
  - "--set-secrets=DATABASE_HOST=WTG_DB_HOST:latest,DATABASE_PORT=WTG_DB_PORT:latest,DATABASE_USER=WTG_DB_USER:latest,DATABASE_PASSWORD=WTG_DB_PASSWORD:latest,DATABASE_NAME=WTG_DB_NAME:latest,POLYGONSCAN_API_KEY=WTG_POLYGONSCAN_API_KEY:latest,ETHERSCAN_API_KEY=WTG_ETHERSCAN_API_KEY:latest,BSCSCAN_API_KEY=WTG_BSCSCAN_API_KEY:latest,SECRET_KEY=WTG_APP_SECRET_KEY:latest"
  - --set-env-vars=ENV=prod
  - --timeout=3600s