FROM python:3.7

COPY ./src/requirements.txt /app/requirements.txt

WORKDIR /app

RUN pip install -r requirements.txt

ARG DATABASE_HOST
ENV DATABASE_HOST $DATABASE_HOST

ARG DATABASE_PORT
ENV DATABASE_PORT $DATABASE_PORT

ARG DATABASE_USER
ENV DATABASE_USER $DATABASE_USER

ARG DATABASE_PASSWORD
ENV DATABASE_PASSWORD $DATABASE_PASSWORD

ARG DATABASE_NAME
ENV DATABASE_NAME $DATABASE_NAME

ARG POLYGONSCAN_API_KEY
ENV POLYGONSCAN_API_KEY $POLYGONSCAN_API_KEY

ARG ETHERSCAN_API_KEY
ENV ETHERSCAN_API_KEY $ETHERSCAN_API_KEY

ARG BSCSCAN_API_KEY
ENV BSCSCAN_API_KEY $BSCSCAN_API_KEY

ARG SECRET_KEY
ENV SECRET_KEY $SECRET_KEY

ARG RPC_ENDPOINTS
ENV RPC_ENDPOINTS $RPC_ENDPOINTS

COPY ./src /app

ENV ENV TEST

ENV PYTHONPATH /app

CMD ["pytest", "tests", "-vv"]