services:
  test:
    env_file:
      - ./src/tests/.env-test
    build:
        context: .
        dockerfile: ./Tests.Dockerfile
    depends_on:
      - postgres

  postgres:
    image: postgres:12.2
    container_name: token_gating_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: token_gating_test